#!/usr/bin/env python3
"""Build a generated, non-personal packet that exercises the workflow entry paths."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


TOPIC = "ai-assisted-vs-autonomous"
SYNTHETIC_SOURCE_URL = "https://example.com/synthetic-ai-workflow-claim"
MCP_URL = "https://modelcontextprotocol.io/docs/getting-started/intro"
NSA_URL = "https://www.nsa.gov/Portals/75/documents/Cybersecurity/CSI_MCP_SECURITY.pdf"
ACCESS_DATE = "2026-08-28"
MARKER = ".video-claim-smoke-test"


def run(command: list[str], cwd: Path) -> None:
    subprocess.run(command, cwd=cwd, check=True, shell=False)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def prepare_output(path: Path, repo_root: Path, replace: bool) -> Path:
    output = path.expanduser().resolve()
    forbidden = {Path("/").resolve(), Path.home().resolve(), repo_root.resolve(), repo_root.parent.resolve()}
    if output in forbidden:
        raise SystemExit(f"Refusing broad smoke-test output: {output}")
    if output.exists() and any(output.iterdir()):
        marker = output / MARKER
        if not replace:
            raise SystemExit(f"Output already exists: {output}. Choose another path or pass --replace.")
        if not marker.is_file():
            raise SystemExit(f"Refusing to replace unmarked directory: {output}")
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)
    write(output / MARKER, "Generated by build_workflow_smoke_test.py")
    return output


def generate_video(path: Path) -> None:
    if shutil.which("ffmpeg") is None:
        raise SystemExit("ffmpeg is required for the workflow smoke test.")
    path.parent.mkdir(parents=True, exist_ok=True)
    run(
        [
            "ffmpeg",
            "-y",
            "-f",
            "lavfi",
            "-i",
            "testsrc2=size=640x360:rate=24",
            "-f",
            "lavfi",
            "-i",
            "anullsrc=channel_layout=mono:sample_rate=16000",
            "-t",
            "4",
            "-c:v",
            "mpeg4",
            "-q:v",
            "5",
            "-c:a",
            "aac",
            str(path),
        ],
        path.parent,
    )


def generate_pdf(path: Path) -> None:
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    except ImportError as exc:
        raise SystemExit("ReportLab is required. Install requirements-smoke-test.txt first.") from exc

    path.parent.mkdir(parents=True, exist_ok=True)
    ink = colors.HexColor("#181814")
    muted = colors.HexColor("#5C5C55")
    paper = colors.HexColor("#F4F1E8")
    blue = colors.HexColor("#2A55FF")
    signal = colors.HexColor("#E5FF67")
    line = colors.HexColor("#C8C4B8")
    styles = getSampleStyleSheet()
    title = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=27,
        leading=30,
        textColor=ink,
        spaceAfter=10,
    )
    label = ParagraphStyle(
        "Label",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=10,
        textColor=blue,
        spaceAfter=5,
    )
    body = ParagraphStyle(
        "Body",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10,
        leading=15,
        textColor=ink,
    )
    small = ParagraphStyle("Small", parent=body, fontSize=8, leading=11, textColor=muted)

    doc = SimpleDocTemplate(
        str(path),
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=17 * mm,
        bottomMargin=16 * mm,
        title="Workflow smoke test: AI-assisted versus autonomous software",
        author="Video Claim Research project",
        subject="Generated packet for deterministic workflow verification",
    )
    story = [
        Paragraph("GENERATED WORKFLOW SMOKE TEST", label),
        Paragraph("Can an MCP-connected app fully self-improve?", title),
        Paragraph(
            "Not demonstrated. MCP can connect an AI application to data, tools, and workflows. That connection does not prove that software can diagnose itself, choose a safe change, implement it correctly, and ship without human review.",
            body,
        ),
        Spacer(1, 8 * mm),
    ]
    evidence = [
        [Paragraph("Observed", small), Paragraph("Missing", small), Paragraph("Assessment", small)],
        [
            Paragraph("A protocol can expose external tools and context.", body),
            Paragraph("Independent performance data and a controlled deployment loop.", body),
            Paragraph("AI-assisted workflow is plausible; human-like autonomy is unproven.", body),
        ],
    ]
    table = Table(evidence, colWidths=[55 * mm] * 3)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), ink),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("BACKGROUND", (0, 1), (-1, -1), paper),
                ("GRID", (0, 0), (-1, -1), 0.6, line),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    rating = Table(
        [[Paragraph("Plausible workflow", body), Paragraph("Overstated claim", body), Paragraph("Medium confidence", body)]],
        colWidths=[55 * mm] * 3,
    )
    rating.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), signal),
                ("BOX", (0, 0), (-1, -1), 0.8, ink),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.extend(
        [
            table,
            Spacer(1, 8 * mm),
            Paragraph("RATING", label),
            rating,
            Spacer(1, 8 * mm),
            Paragraph("SOURCES AND LIMIT", label),
            Paragraph(
                f"MCP introduction: {MCP_URL}<br/>NSA MCP security guidance: {NSA_URL}<br/>The video is generated test media. It is not evidence and does not depict a real claimant or product.",
                small,
            ),
        ]
    )
    doc.build(story)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        default=str(Path(tempfile.gettempdir()) / "video-claim-research-smoke-test"),
        help="Generated workspace path. Defaults to the system temporary directory.",
    )
    parser.add_argument(
        "--replace",
        action="store_true",
        help=f"Replace the target only when it contains the {MARKER} marker.",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    output = prepare_output(Path(args.output), repo_root, args.replace)
    create_topic = repo_root / ".agents/skills/video-claim-research/scripts/create_topic.py"
    extract_assets = repo_root / ".agents/skills/video-claim-research/scripts/extract_media_assets.py"
    audit_topic = repo_root / ".agents/skills/research-packet-audit/scripts/audit_topic.py"

    run(
        [
            sys.executable,
            str(create_topic),
            "--topic",
            TOPIC,
            "--url",
            SYNTHETIC_SOURCE_URL,
            "--root",
            str(output),
            "--date",
            ACCESS_DATE,
        ],
        repo_root,
    )
    topic_dir = output / "materials used/topics" / TOPIC
    media_path = output / "videos to transcribe" / TOPIC / "generated-test-pattern.mp4"
    generate_video(media_path)
    run(
        [sys.executable, str(extract_assets), str(media_path), str(topic_dir), "--every-seconds", "2"],
        repo_root,
    )

    transcript = """# Transcript

00:00-00:04 - No spoken words. A generated test pattern and silence exercise the media pipeline.

The synthetic claim is supplied in `claims.md`; the generated video is not evidence.
"""
    write(topic_dir / "transcript.md", transcript)
    write(output / "transcripts" / f"{TOPIC}.md", f"# Transcript: {TOPIC}\n\n" + transcript.split("\n", 2)[2])
    write(
        topic_dir / "claims.md",
        """# Claims

| Timestamp | Claim | Type | Evidence needed | Status |
|---|---|---|---|---|
| Demo prompt | An MCP-connected app can fully self-improve like a human. | Factual/causal | Repeated autonomous detection, decision, implementation, test, deployment, and measured improvement. | Overstated; not demonstrated. |
""",
    )
    write(
        topic_dir / "links.md",
        f"""# Links: {TOPIC}

| Date accessed | Link | Purpose | Notes |
|---|---|---|---|
| {ACCESS_DATE} | {SYNTHETIC_SOURCE_URL} | Placeholder for generated local test media. | No remote media was downloaded. |
| {ACCESS_DATE} | {MCP_URL} | Primary documentation for MCP's connection role. | Does not establish product autonomy. |
| {ACCESS_DATE} | {NSA_URL} | Independent security guidance and counterweight. | Supports scoped permissions and review. |
""",
    )
    write(
        topic_dir / "source-profile.md",
        """# Source profile

- Source attribution: Generated local test fixture, not a real speaker.
- Evidence scope: Public MCP documentation and security guidance.
- Personal evaluation: None. Only the workflow claim is assessed.
""",
    )
    write(
        topic_dir / "research-notes.md",
        f"""# Research notes

## Acquisition

FFmpeg generated the source file locally. No platform, browser session, or account was accessed.

## Evidence for

MCP documentation supports connecting AI applications to external data, tools, and workflows: {MCP_URL}

## Evidence against or missing

A connection protocol does not prove reliable autonomous diagnosis, product judgment, code changes, tests, or deployment. NSA guidance emphasizes permissions and security boundaries: {NSA_URL}

## Gaps and blockers

No blocker. The packet tests structure and commands; it does not evaluate a real product.
""",
    )
    write(
        topic_dir / "report-outline.md",
        """# Report outline

## Bottom line

AI-assisted improvement is plausible. Human-like autonomous self-improvement is not demonstrated.

## Evidence

MCP supports connections. Independent performance, safety, and deployment evidence is missing.

## Opinion

Plausible workflow, overstated claim, medium confidence.

## Question

Which measured product outcome would prove the generated change helped?
""",
    )
    write(topic_dir / "ocr" / "README.md", "# OCR\n\nNo OCR was required for the generated test pattern.")
    write(
        topic_dir / "evidence" / "research-summary.md",
        f"# Research summary\n\nMCP source: {MCP_URL}\n\nSecurity counterpoint: {NSA_URL}",
    )
    generate_pdf(output / "pdfs" / f"{TOPIC}.pdf")
    # This is a synthetic contract fixture, not a human review of real research.
    write(topic_dir / "publication-review.json", json.dumps({
        "policy_version": 1, "original_visuals_only": True,
        "claim_focused": True, "rights_privacy_reviewed": True,
        "reviewer": "synthetic smoke-test fixture", "reviewed_at": ACCESS_DATE,
        "report_sha256": hashlib.sha256((output / "pdfs" / f"{TOPIC}.pdf").read_bytes()).hexdigest()
    }, indent=2))
    run([sys.executable, str(audit_topic), TOPIC, "--root", str(output)], repo_root)
    print(f"smoke_test={output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
